export const CATEGORIES = {
    BUSINESS: 'BUSINESS',
    CHEMISTRY: 'CHEMISTRY',
    MUSIC: 'MUSIC',
    IT: 'IT',
    COMPUTER_HARDWARE: 'COMPUTER_HARDWARE',
    ASSIGNMENT: 'ASSIGNMENT',
    UI_UX: 'UI_UX',
    AGRICULTURE: 'AGRICULTURE',
    TECH_TOOLS: 'TECH_TOOLS',
    MATHEMATICS: 'MATHEMATICS',
    PROGRAMMING: 'PROGRAMMING',
    DEVOPS: 'DEVOPS',
    CONTENT_CREATION: 'CONTENT_CREATION',
    BIOLOGY: 'BIOLOGY',
    ARTIFICIAL_INTELLIGENCE: 'ARTIFICIAL_INTELLIGENCE'
}